### ISSUE TITLE
Create a working prototype of an application connecting to a SQLite database

### ISSUE THREAD

**Issue by fredym** [QMDevTeam/QMPDA#7]
This will help understanding the requirements, dependencies and implications of replacing the database engine.

**Comment by jgarciab80** [comment]
These are my findings related to this task:
1. The application must be written in VB.NET and must use a .NET CF (Compact Framework)
1.1. Most likely that the application should use .NET CF 2.0 (this implies VS2005), since the original QMPDA App is using that framework
1.2. If any problem is found, there will be attempts to build an App that uses .NET CF 3.5 (this implies VS2008)
1.2.1. If this is the case, this mean that the original application should be migrated to .NET CF 3.5
2. SQLite Database Manager must be installed on the Mobile Device
2.1 According to this site http://sqlite-wince.sourceforge.net/, there exist a complete port that works for Mobile Devices.
3. There will be an attempt to use managed code to access the SQLite Database Manager from .NET CF App.
3.1 There's a Native project that is found here: http://system.data.sqlite.org/index.html/doc/trunk/www/downloads.wiki. The name for the library that will work for us is: "Precompiled Binaries for Windows CE (.NET Compact Framework 3.5) ". Note: if we pick this option, then we need to do the task on bullet 1.2.1.
3.2. There's a legacy project found here: http://sourceforge.net/projects/sqlite-dotnet2/. The interesting part here is that this claims to support "Full and Compact Framework 2.0 and 3.5". If we get this working, then this should be fine in order to connect to SQLite DB from a .NET 2.0 Compact Framework Application, running on a Windows Mobile device.

**Comment by jgarciab80** [comment]
Adding bullet to the previous list:
4. ANSI SQL should be supported and Inserts, Updates and Deletes should be completely functional.

**Comment by jgarciab80** [comment]
Comment on point No. 2:

I realized that there's no such thing as a "SQLite Database Manager", since the SQLite databases are stored in single files and there's only command line interpreters and visual query analyzers that allows easy manipulation. Thus, DB acess will be provided by the Database Layer application. 

This is an example of "SQLmd_dbg.exe" app for Windows CE, "connecting" (in fact, it is opening a single file) to a SQLite DB:
![sqlite1](https://f.cloud.github.com/assets/4589234/752042/975b404e-e52d-11e2-8e39-c3d02d44df8a.jpg)
![sqlite2](https://f.cloud.github.com/assets/4589234/752041/9710e968-e52d-11e2-8de0-45bfa2131965.jpg)

Comment: connection string is only the file name itself.

**Comment by jgarciab80** [comment]
Successful creation of .NET CF 2.0 application that has database access to SQLite databases.
Key task: Get ADO.NET 2.0 working for .NET CF 2.0
[x] Download Source code file SQLite-1.0.66.0-source.zip from here: http://sourceforge.net/projects/sqlite-dotnet2/files/SQLite%20for%20ADO.NET%202.0/1.0.66.0/ (latest version is 1.0.66)
[x] Project source code is targeted for Framework 2.0, however Visual Studio version for .sln (solution) and .csproj (projects) is VS2008.
[x] IMPORTANT: Perform a manual downgrade from VS2008 to VS2005.
    > This task is accomplished by doing the following steps.
    1. Open the solution file named "SQLite.NET.sln" (this is on root of relative folder) with your favorite text editor.
    Search for the value "10.0" (without the quotes) on the second line, and replace the value "10.0" by "9.00"
    In the third line, replace the value from "#Visual Studio 2008" to "#Visual Studio 2005"
    Save and close the modified solution file.
    2. Open the file named "SQLite.Interop.vcproj" (this file is inside the folder named "SQLite.Interop") with your favorite text editor.
    Search for the text "9.00" found on the fourth line, and replace it with the text "8.00"
    SMALL AND SHARP FIX: the author forgot to increment Project's version so it is stuck on 1.065. We need to set the DLL version, so if we build it then 
    it will be automatically recognized during Deployment (IMPORTANT: otherwise we will need to perform a manual renaming of Interop dll)
        - Go to line 336 (OutputFile="../bin/CompactFramework/$(InputName).065.DLL") and change the value "065" for "066" (without quotes)
        - Go to line 677 (OutputFile="../bin/CompactFramework/$(InputName).065.DLL") and change the value "065" for "066" (without quotes)
    Save and close the modified project file.
        The manual downgrade has been accomplished successfully.
[x] Open the solution file with VS2005
        When opening it, there will be a couple of warnings regarding Linq libraries not found. IMPORTANT: Ignore them! We are safe to continue without Linq 
    because VS2005 did not include support for those libraries at that time. Also those libraries are targeted for the "Desktop version" of Sqlite3 library 
    and in this build we are focusing exclusively in the CompactFramework version. 
    For the previous reason, the projects "System.Data.SQLite.Linq" and "testlinq" will be unloaded from the solution. This is perfectly normal.
    Again, since we are focusing on building a Compact Framework library, we need to exclude or unload projects from the solution:
        - Unload or exclude: 
            + SQLite.Designer
            + System.Data.SQLite - ManagedOnly
            + System.Data.SQLite - Netmodule
            + test
     > On solution, go to Properties, Configuration Manager Properties, and check all the checkboxes
     > Set the configuration to Debug (IMPORTANT: just "Debug", not "Debug - Stock")
     > Change the architecture targeted to Compact Framework ARMv4.0
     > Set "testce" as the startup project
     > At this point we have a complete solution ready to build a SQLite library for Compact Framework 2.0, that has been testest to run smootly without any warnings and inconvenients.
![solution](https://f.cloud.github.com/assets/4589234/786609/fc72ff68-eabd-11e2-9469-410ba5d70106.PNG)

```
 [x] Build and Deploy your application. The result will be found on the folder \bin\CompactFramework (relative path on Destkop PC where Project was compiled  
with VS2005) and on the Mobile Device (or emulator) will be located at absolute path \Program Files\testce
 [x] Run your application from Visual Studio 2005
```

![pocketpc](https://f.cloud.github.com/assets/4589234/786610/10321976-eabe-11e2-8e4a-24e3efea92c4.PNG)

```
1. The result will be a SQLite Database located on Device's root folder "test.db3". IMPORTANT: the source code included a Database with encryption; that
was accomplished by adding a "Password" keyword to the connection string. You may want to remove the password/encryption to the final Database to obtain
it in "plain" form.
    - Go to "testce" project
    - Open file named "Program.cs"
    - Go to Line 47 (cnn.ConnectionString = "Data Source=test.db3;Password=yVXL39etehPX";), remove the "Password" attribute (the resulting line will
     be: cnn.ConnectionString = "Data Source=test.db3;";)
    - Clean, Build, Deploy and Run your solution, do it in that order.
    - You can take the resulting Database file "test.db3" from device's root folder; that one will be a valid SQLite Database (without encryption).
    - Inspect the resulting database using your favorite SQLite Database manager
```

![sqlitemanager](https://f.cloud.github.com/assets/4589234/786611/1b434d3a-eabe-11e2-87cd-6f7417a9549a.png)

[x] Although the whole solution was implement for "Pocket PC 2003 SE", you can port that easily to run on Windows Mobile 5.0 (Tested)

**Comment by gerardlopez2001** [comment]
Referenced in Trello: https://trello.com/c/pnEF49F5
